name: afno_app
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1
  bloc: ^8.1.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  go_router: ^10.0.0
  flutter_hooks: ^0.20.1
  json_annotation: ^4.7.0
  url_strategy: ^0.2.0
  url_launcher: ^6.1.7
  path_provider: ^2.0.11
  get_it: ^7.2.0
  freezed: ^2.4.2
  freezed_annotation: ^2.2.0
  dio: ^5.3.2
  shared_preferences: ^2.0.16
  cached_network_image: ^3.2.3
  flutter_svg: ^2.0.7
  flutter_dotenv: ^5.1.0
  json_serializable: ^6.7.1
  google_maps_flutter: ^2.4.0
  google_maps_flutter_web: ^0.5.3
  carousel_slider: ^4.2.1
  loading_skeleton_niu: ^0.0.1
  flutter_widget_from_html_core: ^0.10.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - assets/
    - .env.development

  fonts:
    - family: ProximaNova
      fonts:
        - asset: assets/fonts/ProximaNovaThin.otf
        - asset: assets/fonts/ProximaNovaRegular.otf
        - asset: assets/fonts/ProximaNovaBold.otf
          weight: 700
